CREATE TABLE `resort`.`resort_details` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `LOCATION` VARCHAR(45) NULL,
  `CHECK_IN_TIME` TIME NULL,
  `CHECK_OUT_TIME` TIME NULL,
  `CREATE_BY` VARCHAR(45) NULL,
  `CREATE_DATE` DATE NULL,
  `UPDATE_DATE` DATE NULL,
  `OWNER` VARCHAR(45) NULL,
  `PRICE_PER_DAY` DOUBLE NULL,
  PRIMARY KEY (`ID`));
